### ISSUE TITLE
Expand explanation code coverage

### ISSUE THREAD

**Issue by wlangera** [b-cubed-eu/documentation#71]
After solving [this issue](https://github.com/b-cubed-eu/impIndicator/issues/33).
Explanation of code coverage is not very clear on the documentation website:

**1.**  Go to https://about.codecov.io/ and login with your GitHub account. Search for your package repository in the B-Cubed organisation. Copy the token.
**2.** Configure code coverage by running this code in your R project

```r
#install.packages("covr")
library(covr)
codecov(token = "YOUR_TOKEN_GOES_HERE") 
```

**3.** Go to your package repository on GitHub. Choose Settings > Secrets. Create a new repository secret with name CODECOV_TOKEN and the token you copied as value ([link](https://docs.codecov.com/docs/adding-the-codecov-token)).
**4.** Add GitHub action

```r
usethis::use_github_action("test-coverage", badge = TRUE)
```

**5.** Add codecov.yml

```
comment: true

coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    patch:
      default:
        target: auto
        threshold: 10%
        informational: true
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
```
