### ISSUE TITLE
automate Rmd to md routine

### ISSUE THREAD

**Issue by sannegovaert** [b-cubed-eu/documentation#86]
Adapt the rmd_to_md.rmd script:
- use a csv to list all the packages, titles, lables, required packages and where the package logo lives

**Comment by peterdesmet** [comment]
As mentioned, a yaml file might be easier to maintain:

```yaml
gcube:
- source: https://raw.githubusercontent.com/b-cubed-eu/gcube/refs/heads/main/README.Rmd
  title: Introduction
  sidebar_label: Introduction
- source: https://raw.githubusercontent.com/b-cubed-eu/gcube/refs/heads/main/vignettes/articles/occurrence-process.Rmd
  title: Simulating the occurrence process
  sidebar_label: Occurrence process
  dependencies: sf, dplyr, ggplot2, tidyterra

dubicube:
- source: https://example.com
  title: Example
```

Which you can read with:

```R
library(yaml)
library(purrr)
yaml <- yaml::read_yaml("vignettes.yml")

my_pkg <- "gcube"
my_vignettes <- tibble(purrr::map_df(
  yaml[[my_pkg]], # Select package
  ~ as.data.frame(., stringsAsFactors = FALSE)
))
```
